frr defaults traditional
hostname r4
service integrated-vtysh-config
log stdout informational
!
bfd
 profile FAST
  detect-multiplier 3
  receive-interval 100
  transmit-interval 100
 exit
!
interface lo
 ip address 10.255.0.4/32
 ip router isis SF
 isis passive
!
interface eth1
 ip address 10.0.24.1/31
 ip router isis SF
 isis network point-to-point
 isis metric level-2 10
 isis bfd
 isis bfd profile FAST
!
interface eth2
 ip address 10.0.34.1/31
 ip router isis SF
 isis network point-to-point
 isis metric level-2 20
 isis bfd
 isis bfd profile FAST
!
interface eth3
 ip address 198.51.100.1/24
 ip router isis SF
 isis passive
!
router isis SF
 net 49.0001.0000.0000.0004.00
 is-type level-2-only
 metric-style wide
 lsp-gen-interval 1
 spf-interval 1
 log-adjacency-changes
!
router bgp 65000
 bgp router-id 10.255.0.4
 neighbor 10.255.0.1 remote-as 65000
 neighbor 10.255.0.1 update-source lo
 address-family ipv4 unicast
  network 198.51.100.0/24
  neighbor 10.255.0.1 next-hop-self
 exit-address-family
!
line vty
