#!/usr/bin/env python3
"""Compile and cross-check the public contracts against the HTTP implementation."""

from __future__ import annotations

import hashlib
import json
import os
import re
import subprocess
import tempfile
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

import yaml


ROOT = Path(__file__).resolve().parents[2]
OPENAPI = ROOT / "api/openapi.yaml"
SERVER = ROOT / "internal/api/server.go"
GRPC_SERVER = ROOT / "internal/api/grpc.go"
PROTO_ROOT = ROOT / "api/proto"
PROTO_FILES = [
    PROTO_ROOT / "starfabric/v1/topology.proto",
    PROTO_ROOT / "starfabric/v1/control.proto",
]
REPORT = ROOT / "reports/api-contract.json"
GENERATED = [
    ROOT / "gen/starfabric/v1/topology.pb.go",
    ROOT / "gen/starfabric/v1/control.pb.go",
    ROOT / "gen/starfabric/v1/control_grpc.pb.go",
]


def resolve_ref(document: dict[str, Any], reference: str) -> Any:
    if not reference.startswith("#/"):
        raise AssertionError(f"external OpenAPI reference is not pinned: {reference}")
    current: Any = document
    for component in reference[2:].split("/"):
        current = current[component.replace("~1", "/").replace("~0", "~")]
    return current


def check_refs(document: dict[str, Any], value: Any) -> int:
    count = 0
    if isinstance(value, dict):
        if "$ref" in value:
            resolve_ref(document, value["$ref"])
            count += 1
        for child in value.values():
            count += check_refs(document, child)
    elif isinstance(value, list):
        for child in value:
            count += check_refs(document, child)
    return count


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def main() -> None:
    document = yaml.safe_load(OPENAPI.read_text(encoding="utf-8"))
    assert document["openapi"].startswith("3.1."), "OpenAPI 3.1 is required"
    assert document["security"] == [{"bearerAuth": []}], "bearer auth must be the API default"
    assert document["paths"]["/healthz"]["get"]["security"] == []
    assert document["paths"]["/readyz"]["get"]["security"] == []
    reference_count = check_refs(document, document)

    implementation = SERVER.read_text(encoding="utf-8")
    implemented = {
        (method.lower(), path)
        for method, path in re.findall(r'HandleFunc\("(GET|POST|PUT|DELETE|PATCH) ([^"]+)"', implementation)
    }
    documented = {
        (method, path)
        for path, item in document["paths"].items()
        for method in item
        if method in {"get", "post", "put", "delete", "patch"}
    }
    if implemented != documented:
        raise AssertionError(
            f"HTTP/OpenAPI route drift: undocumented={sorted(implemented - documented)} "
            f"unimplemented={sorted(documented - implemented)}"
        )
    for method, path in sorted(documented):
        operation = document["paths"][path][method]
        responses = operation.get("responses", {})
        assert any(str(code).startswith("2") for code in responses), f"{method} {path}: success response missing"

    with tempfile.TemporaryDirectory(prefix="starfabric-proto-") as temp:
        descriptor = Path(temp) / "starfabric.pb"
        command = [
            "protoc",
            f"-I{PROTO_ROOT}",
            f"--descriptor_set_out={descriptor}",
            "--include_imports",
            *(str(path) for path in PROTO_FILES),
        ]
        completed = subprocess.run(command, check=False, capture_output=True, text=True)
        if completed.returncode:
            raise AssertionError(f"Protobuf compilation failed:\n{completed.stderr}")
        descriptor_bytes = descriptor.stat().st_size
        assert descriptor_bytes > 0

    for generated in GENERATED:
        assert generated.is_file() and generated.stat().st_size > 0, f"missing generated Go API: {generated}"
        assert "Code generated by protoc" in generated.read_text(encoding="utf-8")
    generated_grpc = GENERATED[-1].read_text(encoding="utf-8")
    rpc_count = len(re.findall(r"^\s*rpc\s+", PROTO_FILES[1].read_text(encoding="utf-8"), re.MULTILINE))
    assert rpc_count == 13
    assert "type StarFabricControlClient interface" in generated_grpc
    assert "type StarFabricControlServer interface" in generated_grpc
    assert "RegisterStarFabricControlServer" in generated_grpc
    assert "RegisterStarFabricControlServer" in GRPC_SERVER.read_text(encoding="utf-8")

    environment = os.environ.copy()
    environment["GOCACHE"] = str(ROOT / ".cache/go-build")
    environment["GOPROXY"] = "off"
    grpc_test = subprocess.run(
        [
            "go",
            "test",
            "-buildvcs=false",
            "./internal/api",
            "-run",
            "^TestGeneratedGRPCClientExecutesEveryV1RPC$",
            "-count=1",
        ],
        cwd=ROOT,
        env=environment,
        check=False,
        capture_output=True,
        text=True,
    )
    if grpc_test.returncode:
        raise AssertionError(f"generated gRPC client/server test failed:\n{grpc_test.stdout}\n{grpc_test.stderr}")

    report = {
        "schema_version": 1,
        "success": True,
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "checks": {
            "openapi_version": document["openapi"],
            "documented_http_operations": len(documented),
            "implementation_routes": len(implemented),
            "route_sets_equal": True,
            "resolved_local_references": reference_count,
            "protobuf_descriptor_bytes": descriptor_bytes,
            "generated_go_messages": len(GENERATED) == 3,
            "generated_grpc_client_server": True,
            "grpc_generated_client_all_rpcs": rpc_count,
            "predictive_api_documented": all(
                path in document["paths"]
                for path in ["/api/v1/predictive/forecast", "/api/v1/predictive/schedules"]
            ),
        },
        "artifacts": {
            "openapi_sha256": sha256(OPENAPI),
            "topology_proto_sha256": sha256(PROTO_FILES[0]),
            "control_proto_sha256": sha256(PROTO_FILES[1]),
            "generated_topology_go_sha256": sha256(GENERATED[0]),
            "generated_control_go_sha256": sha256(GENERATED[1]),
            "generated_grpc_go_sha256": sha256(GENERATED[2]),
        },
    }
    REPORT.parent.mkdir(parents=True, exist_ok=True)
    temporary = REPORT.with_suffix(".json.tmp")
    temporary.write_text(json.dumps(report, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    os.replace(temporary, REPORT)
    print(
        f"PASS: {len(documented)} HTTP operations match OpenAPI; "
        f"Protobuf descriptor={descriptor_bytes} bytes"
    )


if __name__ == "__main__":
    main()
