version: 2
updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: gomod
    directory: /tests/ondatra
    schedule:
      interval: weekly
  - package-ecosystem: cargo
    directory: /onboard
    schedule:
      interval: weekly
  - package-ecosystem: pip
    directory: /tools
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
