router bgp 65000
 bgp router-id 10.255.0.1
 no bgp ebgp-requires-policy
 neighbor 10.0.15.1 remote-as 65001
 !
 address-family link-state link-state
  neighbor 10.0.15.1 activate
 exit-address-family
exit

