frr defaults traditional
hostname control-pce
service integrated-vtysh-config
log stdout informational
!
interface eth1
 ip address 10.0.15.1/31
!
ip route 10.255.0.1/32 10.0.15.0
!
router bgp 65001
 bgp router-id 10.255.0.5
 no bgp ebgp-requires-policy
 neighbor 10.0.15.0 remote-as 65000
 !
 address-family link-state link-state
  neighbor 10.0.15.0 activate
 exit-address-family
!
line vty
