frr defaults traditional
hostname control-backup
service integrated-vtysh-config
log stdout informational
!
interface lo
 ip address 10.255.0.3/32
 ipv6 address 2001:db8:ffff::3/128
 ip router isis SF
 ipv6 router isis SF
 isis passive
!
interface eth1
 ip address 10.0.13.1/31
 ipv6 address 2001:db8:13::2/64
 ip router isis SF
 ipv6 router isis SF
 isis network point-to-point
 isis metric level-2 20
 isis hello-interval 1
 isis hello-multiplier 3
 link-params
  max-bw 125000000
 exit-link-params
!
interface eth2
 ip address 10.0.34.0/31
 ipv6 address 2001:db8:34::1/64
 ip router isis SF
 ipv6 router isis SF
 isis network point-to-point
 isis metric level-2 20
 isis hello-interval 1
 isis hello-multiplier 3
 link-params
  max-bw 125000000
 exit-link-params
!
router isis SF
 net 49.0001.0000.0000.0003.00
 is-type level-2-only
 metric-style wide
 lsp-gen-interval 1
 spf-interval 1
 mpls-te on
 mpls-te router-address 10.255.0.3
 segment-routing srv6
  locator BACKUP
 exit
exit
!
segment-routing
 srv6
  locators
   locator BACKUP
    prefix fc00:0:3::/64
   exit
  exit
 exit
exit
!
line vty
