frr defaults traditional
hostname control-tail
service integrated-vtysh-config
log stdout informational
!
interface lo
 ip address 10.255.0.4/32
 ipv6 address 2001:db8:ffff::4/128
 ipv6 address 2001:db8:feed::1/128
 ip router isis SF
 ipv6 router isis SF
 isis passive
!
interface eth1
 ip address 10.0.24.1/31
 ipv6 address 2001:db8:24::2/64
 ip router isis SF
 ipv6 router isis SF
 isis network point-to-point
 isis metric level-2 10
 isis hello-interval 1
 isis hello-multiplier 3
 link-params
  max-bw 125000000
 exit-link-params
!
interface eth2
 ip address 10.0.34.1/31
 ipv6 address 2001:db8:34::2/64
 ip router isis SF
 ipv6 router isis SF
 isis network point-to-point
 isis metric level-2 20
 isis hello-interval 1
 isis hello-multiplier 3
 link-params
  max-bw 125000000
 exit-link-params
!
router isis SF
 net 49.0001.0000.0000.0004.00
 is-type level-2-only
 metric-style wide
 lsp-gen-interval 1
 spf-interval 1
 mpls-te on
 mpls-te router-address 10.255.0.4
 segment-routing srv6
  locator TAIL
 exit
exit
!
segment-routing
 srv6
  locators
   locator TAIL
    prefix fc00:0:4::/64
   exit
  exit
 exit
exit
!
line vty
