segment-routing
 traffic-eng
  policy color 100 endpoint 10.255.0.4
   name PCEP-COMPUTED-PATH
   candidate-path preference 200 name REMOTE dynamic
  exit
  !
  pcep
   pce LAB-PCE
    address ip 10.0.15.1
   exit
   !
   pcc
    peer LAB-PCE precedence 10
   exit
  exit
 exit
exit

