frr defaults traditional
hostname r1
service integrated-vtysh-config
log stdout informational
!
interface lo
 ip address 10.255.0.1/32
 ip router isis SF
 isis passive
!
interface eth1
 description host-h1
 ip address 192.0.2.1/24
 ip router isis SF
 isis passive
!
interface eth2
 description r1-to-r2-primary
 ip address 10.0.12.0/31
 ip router isis SF
 isis network point-to-point
 isis circuit-type level-2-only
 isis metric level-2 10
 isis hello-interval 3
 isis hello-multiplier 3
!
interface eth3
 description r1-to-r3-backup
 ip address 10.0.13.0/31
 ip router isis SF
 isis network point-to-point
 isis circuit-type level-2-only
 isis metric level-2 20
 isis hello-interval 3
 isis hello-multiplier 3
!
router isis SF
 net 49.0001.0000.0000.0001.00
 is-type level-2-only
 metric-style wide
 log-adjacency-changes
!
line vty
