frr defaults traditional
hostname gw-a
service integrated-vtysh-config
log stdout informational
!
interface lo
 ip address 10.255.0.4/32
 ip address 203.0.113.4/32
 ip address 203.0.113.5/32
 ip ospf area 0.0.0.0
 ip ospf passive
 ipv6 address 2001:db8:ffff::4/128
 ip router isis SF
 ipv6 router isis SF
 isis passive
 ipv6 ospf6 area 0.0.0.0
!
interface eth1
 ip address 10.0.24.1/31
 ipv6 address 2001:db8:24::2/64
 ip ospf area 0.0.0.0
 ip ospf cost 10
 ip ospf network point-to-point
 ipv6 ospf6 area 0.0.0.0
 ipv6 ospf6 cost 10
 ipv6 ospf6 network point-to-point
 ip router isis SF
 ipv6 router isis SF
 isis network point-to-point
 isis metric level-2 10
!
interface eth2
 ip address 10.0.34.1/31
 ipv6 address 2001:db8:34::2/64
 ip ospf area 0.0.0.0
 ip ospf cost 20
 ip ospf network point-to-point
 ipv6 ospf6 area 0.0.0.0
 ipv6 ospf6 cost 20
 ipv6 ospf6 network point-to-point
 ip router isis SF
 ipv6 router isis SF
 isis network point-to-point
 isis metric level-2 20
!
router ospf
 ospf router-id 10.255.0.4
 timers throttle spf 0 50 500
!
router ospf6
 ospf6 router-id 10.255.0.4
 timers throttle spf 0 50 500
!
router isis SF
 net 49.0001.0000.0000.0004.00
 is-type level-2-only
 metric-style wide
 lsp-gen-interval 1
 spf-interval 1
 segment-routing on
 segment-routing global-block 16000 23999
 segment-routing prefix 10.255.0.4/32 index 4
!
line vty
