apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "starfabric.fullname" . }}-scenario
  labels:
    {{- include "starfabric.labels" . | nindent 4 }}
data:
  scenario.json: |-
{{ .Values.scenario | toPrettyJson | indent 4 }}
