apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "starfabric.fullname" . }}
  labels:
    {{- include "starfabric.labels" . | nindent 4 }}
automountServiceAccountToken: {{ .Values.ha.enabled }}
