apiVersion: v1
kind: Service
metadata:
  name: {{ include "starfabric.fullname" . }}
  labels:
    {{- include "starfabric.labels" . | nindent 4 }}
spec:
  selector:
    app.kubernetes.io/name: {{ include "starfabric.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
    - name: health
      port: 8081
      targetPort: health
