{{- if .Capabilities.APIVersions.Has "monitoring.coreos.com/v1" }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "starfabric.fullname" . }}
  labels:
    {{- include "starfabric.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "starfabric.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  endpoints:
    - port: health
      path: /metrics
      interval: 15s
{{- end }}
