apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: starfabric
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://REPLACE_WITH_YOUR_GIT_REPOSITORY
    targetRevision: main
    path: deploy/helm/starfabric
    helm:
      valueFiles: [values.yaml, values-ha.yaml]
  destination:
    server: https://kubernetes.default.svc
    namespace: starfabric
  syncPolicy:
    automated: {prune: true, selfHeal: true}
    syncOptions: [CreateNamespace=true]
  revisionHistoryLimit: 10
